const PRODUCTS = [
    // Fruits
    {
        category: "Fruits",
        price: "$1",
        stocked: true,
        productName: "Apple",
        origin: "Asia",
    },
    {
        category: "Fruits",
        price: "$1",
        stocked: true,
        productName: "Dragonfruit",
        origin: "Southeast Asia",
    },
    {
        category: "Fruits",
        price: "$2",
        stocked: false,
        productName: "Passionfruit",
        origin: "South America",
    },
    {
        category: "Fruits",
        price: "$3",
        stocked: true,
        productName: "Mango",
        origin: "South Asia",
    },
    {
        category: "Fruits",
        price: "$2",
        stocked: false,
        productName: "Banana",
        origin: "Southeast Asia",
    },
    {
        category: "Fruits",
        price: "$4",
        stocked: true,
        productName: "Pineapple",
        origin: "South America",
    },
    {
        category: "Fruits",
        price: "$3",
        stocked: false,
        productName: "Orange",
        origin: "China",
    },
    {
        category: "Fruits",
        price: "$1",
        stocked: true,
        productName: "Strawberry",
        origin: "Europe",
    },
    {
        category: "Fruits",
        price: "$1",
        stocked: false,
        productName: "Cherry",
        origin: "Europe",
    },
    {
        category: "Fruits",
        price: "$2",
        stocked: true,
        productName: "Grape",
        origin: "Middle East",
    },
    {
        category: "Fruits",
        price: "$2",
        stocked: false,
        productName: "Kiwi",
        origin: "China",
    },
    {
        category: "Fruits",
        price: "$3",
        stocked: true,
        productName: "Peach",
        origin: "China",
    },
    {
        category: "Fruits",
        price: "$3",
        stocked: false,
        productName: "Plum",
        origin: "Europe",
    },
    {
        category: "Fruits",
        price: "$1",
        stocked: true,
        productName: "Pear",
        origin: "China",
    },
    {
        category: "Fruits",
        price: "$1",
        stocked: false,
        productName: "Watermelon",
        origin: "Africa",
    },
    {
        category: "Fruits",
        price: "$2",
        stocked: true,
        productName: "Blueberry",
        origin: "North America",
    },
    {
        category: "Fruits",
        price: "$2",
        stocked: false,
        productName: "Raspberry",
        origin: "Europe",
    },
    {
        category: "Fruits",
        price: "$3",
        stocked: true,
        productName: "Blackberry",
        origin: "Europe",
    },
    {
        category: "Fruits",
        price: "$4",
        stocked: false,
        productName: "Pomegranate",
        origin: "Iran",
    },
    {
        category: "Fruits",
        price: "$3",
        stocked: true,
        productName: "Lemon",
        origin: "Asia",
    },
    {
        category: "Fruits",
        price: "$1",
        stocked: false,
        productName: "Lime",
        origin: "Southeast Asia",
    },
    {
        category: "Fruits",
        price: "$2",
        stocked: true,
        productName: "Fig",
        origin: "Asia",
    },
    {
        category: "Fruits",
        price: "$3",
        stocked: false,
        productName: "Papaya",
        origin: "Central America",
    },
    {
        category: "Fruits",
        price: "$1",
        stocked: true,
        productName: "Cantaloupe",
        origin: "Africa",
    },
    {
        category: "Fruits",
        price: "$2",
        stocked: false,
        productName: "Avocado",
        origin: "North America",
    },
    {
        category: "Fruits",
        price: "$3",
        stocked: true,
        productName: "Guava",
        origin: "South America",
    },
    {
        category: "Fruits",
        price: "$1",
        stocked: false,
        productName: "Lychee",
        origin: "Asia",
    },
    {
        category: "Fruits",
        price: "$2",
        stocked: true,
        productName: "Tangerine",
        origin: "Europe",
    },
    {
        category: "Fruits",
        price: "$3",
        stocked: false,
        productName: "Persimmon",
        origin: "Asia",
    },
    {
        category: "Fruits",
        price: "$1",
        stocked: true,
        productName: "Coconut",
        origin: "Oceania",
    },
    {
        category: "Fruits",
        price: "$2",
        stocked: false,
        productName: "Date",
        origin: "Middle East",
    },
    // Vegetables
    {
        category: "Vegetables",
        price: "$2",
        stocked: true,
        productName: "Spinach",
        origin: "Central and Western Asia",
    },
    {
        category: "Vegetables",
        price: "$4",
        stocked: false,
        productName: "Pumpkin",
        origin: "North America",
    },
    {
        category: "Vegetables",
        price: "$1",
        stocked: true,
        productName: "Peas",
        origin: "Mediterranean",
    },
    {
        category: "Vegetables",
        price: "$3",
        stocked: false,
        productName: "Carrot",
        origin: "Persia",
    },
    {
        category: "Vegetables",
        price: "$2",
        stocked: true,
        productName: "Broccoli",
        origin: "Europe",
    },
    {
        category: "Vegetables",
        price: "$3",
        stocked: false,
        productName: "Cauliflower",
        origin: "Asia",
    },
    {
        category: "Vegetables",
        price: "$1",
        stocked: true,
        productName: "Tomato",
        origin: "South America",
    },
    {
        category: "Vegetables",
        price: "$1",
        stocked: false,
        productName: "Cucumber",
        origin: "India",
    },
    {
        category: "Vegetables",
        price: "$2",
        stocked: true,
        productName: "Bell Pepper",
        origin: "Central and South America",
    },
    {
        category: "Vegetables",
        price: "$2",
        stocked: false,
        productName: "Eggplant",
        origin: "Southeast Asia",
    },
    {
        category: "Vegetables",
        price: "$3",
        stocked: true,
        productName: "Lettuce",
        origin: "Egypt",
    },
    {
        category: "Vegetables",
        price: "$4",
        stocked: false,
        productName: "Sweet Potato",
        origin: "Central America",
    },
    {
        category: "Vegetables",
        price: "$3",
        stocked: true,
        productName: "Onion",
        origin: "Central Asia",
    },
    {
        category: "Vegetables",
        price: "$1",
        stocked: false,
        productName: "Garlic",
        origin: "Central Asia",
    },
    {
        category: "Vegetables",
        price: "$2",
        stocked: true,
        productName: "Green Bean",
        origin: "Central and South America",
    },
    {
        category: "Vegetables",
        price: "$2",
        stocked: false,
        productName: "Zucchini",
        origin: "Central and Eastern Europe",
    },
    {
        category: "Vegetables",
        price: "$3",
        stocked: true,
        productName: "Corn",
        origin: "Mexico",
    },
    {
        category: "Vegetables",
        price: "$4",
        stocked: false,
        productName: "Mushroom",
        origin: "Global",
    },
    {
        category: "Vegetables",
        price: "$3",
        stocked: true,
        productName: "Asparagus",
        origin: "Europe, Western Asia",
    },
    {
        category: "Vegetables",
        price: "$1",
        stocked: false,
        productName: "Celery",
        origin: "Mediterranean",
    },
    {
        category: "Vegetables",
        price: "$2",
        stocked: true,
        productName: "Radish",
        origin: "Europe",
    },
    {
        category: "Vegetables",
        price: "$3",
        stocked: false,
        productName: "Beetroot",
        origin: "North America",
    },
    {
        category: "Vegetables",
        price: "$1",
        stocked: true,
        productName: "Artichoke",
        origin: "Mediterranean",
    },
    {
        category: "Vegetables",
        price: "$2",
        stocked: false,
        productName: "Leek",
        origin: "Europe",
    },
    {
        category: "Vegetables",
        price: "$3",
        stocked: true,
        productName: "Fennel",
        origin: "Mediterranean",
    },
    {
        category: "Vegetables",
        price: "$1",
        stocked: false,
        productName: "Chili Pepper",
        origin: "South America",
    },
    {
        category: "Vegetables",
        price: "$2",
        stocked: true,
        productName: "Okra",
        origin: "Africa",
    },
    {
        category: "Vegetables",
        price: "$3",
        stocked: false,
        productName: "Bok Choy",
        origin: "Asia",
    },
    {
        category: "Vegetables",
        price: "$1",
        stocked: true,
        productName: "Parsnip",
        origin: "Europe",
    },
    {
        category: "Vegetables",
        price: "$2",
        stocked: false,
        productName: "Rutabaga",
        origin: "North America",
    },
];

export default PRODUCTS;
